const TAU=Math.PI*2;
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
const lerp=(a,b,t)=>a+(b-a)*t;
const mod=(x,m)=>((x%m)+m)%m;
const rand=(a=1,b)=>b===undefined?Math.random()*a:a+Math.random()*(b-a);
const midiHz=n=>440*Math.pow(2,(n-69)/12);

class PinkDrift{
  constructor(n=7){this.cells=Array.from({length:n},()=>Math.random()*2-1);this.counter=0;}
  next(){this.counter++;let c=this.counter;for(let i=0;i<this.cells.length;i++){if((c&(1<<i))===0)this.cells[i]=Math.random()*2-1;}return this.cells.reduce((a,b)=>a+b,0)/this.cells.length;}
}

class AudioBus{
  constructor(){this.ctx=null;this.master=null;this.dest=null;this.recorder=null;this.chunks=[];}
  async start(){if(this.ctx){await this.ctx.resume();return;}this.ctx=new AudioContext({sampleRate:48000,latencyHint:'interactive'});this.master=this.ctx.createGain();this.master.gain.value=.42;this.dest=this.ctx.createMediaStreamDestination();this.master.connect(this.ctx.destination);this.master.connect(this.dest);}
  bell(freq,index=2.2,decay=.9,brightness=.5,pan=0){if(!this.ctx)return;const t=this.ctx.currentTime;const c=this.ctx.createOscillator(),m=this.ctx.createOscillator(),mg=this.ctx.createGain(),amp=this.ctx.createGain(),p=this.ctx.createStereoPanner();const ratio=1.35+brightness*2.7;c.frequency.setValueAtTime(freq,t);m.frequency.setValueAtTime(freq*ratio,t);mg.gain.setValueAtTime(freq*index,t);mg.gain.exponentialRampToValueAtTime(0.001,t+Math.max(.05,decay*.68));amp.gain.setValueAtTime(.0001,t);amp.gain.exponentialRampToValueAtTime(.17,t+.004);amp.gain.exponentialRampToValueAtTime(.0001,t+decay);p.pan.value=clamp(pan,-1,1);m.connect(mg);mg.connect(c.frequency);c.connect(amp);amp.connect(p);p.connect(this.master);c.start(t);m.start(t);c.stop(t+decay+.08);m.stop(t+decay+.08);}
  beginRecord(){if(!this.dest||this.recorder)return false;this.chunks=[];this.recorder=new MediaRecorder(this.dest.stream);this.recorder.ondataavailable=e=>{if(e.data.size)this.chunks.push(e.data)};this.recorder.onstop=()=>{const blob=new Blob(this.chunks,{type:this.recorder.mimeType||'audio/webm'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tarots-${Date.now()}.webm`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);this.recorder=null;};this.recorder.start();return true;}
  stopRecord(){if(this.recorder)this.recorder.stop();}
}
const audio=new AudioBus();

class StarLab{
  constructor(canvas){this.c=canvas;this.x=canvas.getContext('2d');this.nodes=[];this.edges=[];this.engine='sandpile';this.density=.52;this.motion=.44;this.tone=.64;this.freeze=false;this.last=performance.now();this.acc=0;this.pink=new PinkDrift();this.phases=[0,1.7,4.1];this.walkers=[0,6];this.ca=[];this.avalanche=0;this.fireFlash=[];this.seed();requestAnimationFrame(t=>this.frame(t));}
  seed(){this.nodes=[];for(let i=0;i<12;i++){const a=-Math.PI/2+i*TAU/12+rand(-.16,.16);const r=.27+rand(-.04,.1);this.nodes.push({a,r,e:rand(.1,.6),thr:rand(.82,1.18),ref:0,phase:rand(TAU),omega:rand(.35,.8),state:i%3});}this.rebuildEdges();this.ca=this.nodes.map((_,i)=>i%3);this.walkers=[Math.floor(rand(12)),Math.floor(rand(12))];this.fireFlash=Array(12).fill(0);}
  rebuildEdges(){this.edges=[];for(let i=0;i<12;i++)for(let j=i+1;j<12;j++){const d=Math.min(Math.abs(i-j),12-Math.abs(i-j));let p=.05+this.density*.38+(d<=2?.18:0);if(Math.random()<p)this.edges.push({a:i,b:j,w:rand(.22,.82),mem:rand(0,.2),flash:0});}for(let i=0;i<12;i++){if(!this.edges.some(e=>e.a===i||e.b===i))this.edges.push({a:i,b:(i+1)%12,w:.4,mem:0,flash:0});}}
  neighbours(i){return this.edges.filter(e=>e.a===i||e.b===i).map(e=>({j:e.a===i?e.b:e.a,e}));}
  fire(i,source=-1,energy=1){const n=this.nodes[i];if(n.ref>0)return;n.ref=.08+.26*(1-this.motion);n.e=.04;this.fireFlash[i]=1;this.avalanche++;let incoming=this.edges.find(e=>(e.a===i&&e.b===source)||(e.b===i&&e.a===source));if(incoming){incoming.mem=clamp(incoming.mem+.08);incoming.flash=1;}const midi=52+[0,2,4,7,9,11,14,16,19,21,23,26][i];let ratioBias=incoming?incoming.w:.45;let index=.7+ratioBias*4.8+(this.tone*.8);let decay=.18+this.tone*.95+Math.min(1,this.avalanche/6)*.35;audio.bell(midiHz(midi),index,decay,clamp(.18+ratioBias*.7),Math.sin((i/12)*TAU)*.75);if(this.engine==='sandpile'){for(const {j,e} of this.neighbours(i)){e.mem=clamp(e.mem+.025);this.nodes[j].e+=energy*(.08+.18*e.w)*(1+e.mem*.6);}}}
  tick(dt){if(this.freeze)return;this.avalanche=0;const slow=this.pink.next();this.phases[0]+=dt*(.28+.55*this.motion);this.phases[1]+=dt*(.17+.31*this.motion);this.phases[2]+=dt*(.10+.21*this.motion);for(const e of this.edges){e.mem*=Math.exp(-dt*(.06+.12*(1-this.motion)));e.flash*=Math.exp(-dt*8);}
    if(this.engine==='sandpile')this.tickSand(dt,slow);else if(this.engine==='kuramoto')this.tickKuramoto(dt);else if(this.engine==='walker')this.tickWalker(dt);else this.tickCA(dt);
    for(let i=0;i<12;i++){this.nodes[i].ref=Math.max(0,this.nodes[i].ref-dt);this.fireFlash[i]*=Math.exp(-dt*6);}
  }
  tickSand(dt,slow){for(let i=0;i<12;i++){const n=this.nodes[i];const phase=.16*Math.sin(this.phases[0]+i*.43)+.11*Math.sin(this.phases[1]-i*.29)+.07*Math.sin(this.phases[2]+i*.71);n.e+=dt*(.11+.44*this.motion)*(1+slow*.15);const thr=n.thr-phase;if(n.e>thr&&n.ref<=0)this.fire(i,-1,n.e);}}
  tickKuramoto(dt){const K=.2+this.density*1.8;const phases=this.nodes.map(n=>n.phase);for(let i=0;i<12;i++){let s=0,c=0;for(const {j,e} of this.neighbours(i)){s+=e.w*Math.sin(phases[j]-phases[i]);c+=e.w;}const n=this.nodes[i],old=n.phase;n.phase+=dt*(n.omega*(.8+this.motion*2.8)+K*s/Math.max(1,c));if(Math.floor(old/TAU)!==Math.floor(n.phase/TAU))this.fire(i,-1,.7);}}
  tickWalker(dt){this.acc+=dt*(.7+this.motion*4);if(this.acc<1)return;this.acc-=1;for(let k=0;k<this.walkers.length;k++){const i=this.walkers[k],ns=this.neighbours(i);let total=ns.reduce((s,q)=>s+.1+q.e.w*(1+q.e.mem*2),0),r=rand(total),pick=ns[0];for(const q of ns){r-=.1+q.e.w*(1+q.e.mem*2);if(r<=0){pick=q;break;}}this.walkers[k]=pick.j;this.fire(pick.j,i,.8);}}
  tickCA(dt){this.acc+=dt*(.5+this.motion*3);if(this.acc<1)return;this.acc-=1;const next=this.ca.slice();for(let i=0;i<12;i++){const target=(this.ca[i]+1)%3;const hits=this.neighbours(i).filter(q=>this.ca[q.j]===target).length;if(hits>0&&Math.random()<.25+this.density*.65){next[i]=target;this.fire(i,-1,.6);}}this.ca=next;}
  resize(){const dpr=devicePixelRatio||1,r=this.c.getBoundingClientRect();if(this.c.width!==Math.floor(r.width*dpr)||this.c.height!==Math.floor(r.height*dpr)){this.c.width=Math.floor(r.width*dpr);this.c.height=Math.floor(r.height*dpr);this.x.setTransform(dpr,0,0,dpr,0,0);}}
  pos(i,w,h){const n=this.nodes[i],s=Math.min(w,h),cx=w/2,cy=h/2;return[cx+Math.cos(n.a)*n.r*s,cy+Math.sin(n.a)*n.r*s];}
  draw(){this.resize();const r=this.c.getBoundingClientRect(),w=r.width,h=r.height,ctx=this.x;ctx.clearRect(0,0,w,h);const s=Math.min(w,h),cx=w/2,cy=h/2;ctx.strokeStyle='#26251f';ctx.lineWidth=1;for(const q of [.18,.31,.43]){ctx.beginPath();ctx.arc(cx,cy,s*q,0,TAU);ctx.stroke();}
    for(const e of this.edges){const a=this.pos(e.a,w,h),b=this.pos(e.b,w,h);ctx.strokeStyle=e.flash>.06?`rgba(231,211,134,${.25+.65*e.flash})`:`rgba(122,113,80,${.08+.22*e.mem})`;ctx.lineWidth=1+e.mem*1.4;ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();}
    for(let i=0;i<12;i++){const [x,y]=this.pos(i,w,h),f=this.fireFlash[i],hue=(i*31+320)%360;ctx.fillStyle=`hsla(${hue},70%,70%,${.35+.65*f})`;ctx.shadowBlur=4+f*28;ctx.shadowColor=`hsl(${hue} 80% 65%)`;ctx.beginPath();ctx.arc(x,y,3.6+f*3.8,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#777067';ctx.font='9px monospace';ctx.fillText(String(i+1).padStart(2,'0'),x+8,y+3);}
    ctx.fillStyle='#81785f';ctx.font='11px monospace';ctx.fillText('XII VISIBLE NODES',16,24);ctx.fillStyle='#49473f';ctx.fillText(this.engine.toUpperCase(),16,41);
  }
  frame(t){const dt=Math.min(.05,(t-this.last)/1000);this.last=t;this.tick(dt);this.draw();requestAnimationFrame(x=>this.frame(x));}
}

class WheelLab{
  constructor(canvas){this.c=canvas;this.x=canvas.getContext('2d');this.angle=0;this.omega=0;this.friction=.72;this.spread=.48;this.drive=.56;this.engine='rigid';this.drag=false;this.lastPointer=null;this.last=performance.now();this.teeth=[16,23,31,47,64,89,127,191];this.phase=Array(this.teeth.length).fill(0);this.speed=Array(this.teeth.length).fill(0);this.osc=[];this.gains=[];this.initInput();requestAnimationFrame(t=>this.frame(t));}
  initInput(){const point=e=>{const r=this.c.getBoundingClientRect();return{x:e.clientX-r.left-r.width/2,y:e.clientY-r.top-r.height/2,t:performance.now()}};this.c.addEventListener('pointerdown',e=>{this.c.setPointerCapture(e.pointerId);this.drag=true;this.lastPointer=point(e)});this.c.addEventListener('pointermove',e=>{if(!this.drag)return;const p=point(e),a=Math.atan2(p.y,p.x),b=Math.atan2(this.lastPointer.y,this.lastPointer.x),da=Math.atan2(Math.sin(a-b),Math.cos(a-b)),dt=Math.max(.004,(p.t-this.lastPointer.t)/1000);this.angle+=da;this.omega=lerp(this.omega,da/dt,.7);this.lastPointer=p;});this.c.addEventListener('pointerup',()=>{this.drag=false;this.lastPointer=null});this.c.addEventListener('pointercancel',()=>{this.drag=false;this.lastPointer=null});}
  async ensureAudio(){if(!audio.ctx)return;if(this.osc.length)return;for(let i=0;i<this.teeth.length;i++){const o=audio.ctx.createOscillator(),g=audio.ctx.createGain(),p=audio.ctx.createStereoPanner();o.type=i%3===0?'triangle':'sine';g.gain.value=0;p.pan.value=lerp(-.8,.8,i/(this.teeth.length-1));o.connect(g);g.connect(p);p.connect(audio.master);o.start();this.osc.push(o);this.gains.push(g);}}
  tick(dt){if(!this.drag){this.omega*=Math.exp(-dt*this.friction);if(Math.abs(this.omega)<.002)this.omega=0;this.angle+=this.omega*dt;}const rps=this.omega/TAU;for(let i=0;i<this.teeth.length;i++){let target=rps*this.teeth[i];if(this.engine==='spring'){const follow=.7+i*.22;this.speed[i]+=((target-this.speed[i])*follow)*dt;this.speed[i]*=Math.exp(-dt*.08);}else if(this.engine==='slip'){const slip=1+(i%2?1:-1)*this.spread*.018*Math.sin(this.angle*(i+1)*.13);this.speed[i]=target*slip;}else if(this.engine==='circle'){const K=.1+this.spread*1.2,th=mod(this.phase[i]/TAU,1);const mapped=th+(target*dt)-K/TAU*Math.sin(TAU*th);this.speed[i]=(mapped-th)/dt;this.phase[i]=TAU*mod(mapped,1);}else this.speed[i]=target;
      if(this.engine!=='circle')this.phase[i]+=this.speed[i]*TAU*dt;
      if(this.osc[i]){const hz=clamp(Math.abs(this.speed[i]),8,9000);const amp=Math.abs(this.omega)<.02?0:(.012+.035*this.drive)/(1+i*.08);this.osc[i].frequency.setTargetAtTime(hz,audio.ctx.currentTime,.025);this.gains[i].gain.setTargetAtTime(amp,audio.ctx.currentTime,.04);}}
  }
  resize(){const dpr=devicePixelRatio||1,r=this.c.getBoundingClientRect();if(this.c.width!==Math.floor(r.width*dpr)||this.c.height!==Math.floor(r.height*dpr)){this.c.width=Math.floor(r.width*dpr);this.c.height=Math.floor(r.height*dpr);this.x.setTransform(dpr,0,0,dpr,0,0);}}
  draw(){this.resize();const r=this.c.getBoundingClientRect(),w=r.width,h=r.height,s=Math.min(w,h),ctx=this.x,cx=w/2,cy=h/2,R=s*.33;ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(cx,cy);ctx.rotate(this.angle);ctx.strokeStyle='#b6a76e';ctx.lineWidth=1;for(let k=0;k<5;k++){ctx.beginPath();ctx.arc(0,0,R*(.34+k*.15),0,TAU);ctx.stroke();}for(let i=0;i<48;i++){const a=i*TAU/48,r1=R*.82,r2=R*(i%4===0?.98:.92);ctx.beginPath();ctx.moveTo(Math.cos(a)*r1,Math.sin(a)*r1);ctx.lineTo(Math.cos(a)*r2,Math.sin(a)*r2);ctx.stroke();}ctx.fillStyle='#d9cfaa';ctx.beginPath();ctx.arc(0,0,R*.1,0,TAU);ctx.fill();ctx.restore();ctx.fillStyle='#81785f';ctx.font='11px monospace';ctx.fillText('VIRTUAL TONEWHEEL',16,24);ctx.fillStyle='#49473f';ctx.fillText(this.engine.toUpperCase(),16,41);ctx.fillText(`ω ${this.omega.toFixed(2)} rad/s`,16,58);}
  frame(t){const dt=Math.min(.05,(t-this.last)/1000);this.last=t;this.tick(dt);this.draw();requestAnimationFrame(x=>this.frame(x));}
}

function hexRgb(hex){const n=parseInt(hex.slice(1),16);return[(n>>16)&255,(n>>8)&255,n&255].map(v=>v/255)}
function lin(c){return c<=.04045?c/12.92:Math.pow((c+.055)/1.055,2.4)}
function rgbLab(rgb){let [r,g,b]=rgb.map(lin);const X=(r*.4124+g*.3576+b*.1805)/.95047,Y=(r*.2126+g*.7152+b*.0722),Z=(r*.0193+g*.1192+b*.9505)/1.08883;const f=t=>t>.008856?Math.cbrt(t):7.787*t+16/116;const fx=f(X),fy=f(Y),fz=f(Z);return[116*fy-16,500*(fx-fy),200*(fy-fz)]}
class ColorLab{
  constructor(field,core){this.field=field;this.core=core;this.hex='#cb5d42';this.engine='adapt';this.memory=.82;this.drone=.57;this.rough=.32;this.lab=rgbLab(hexRgb(this.hex));this.adapt=this.lab.slice();this.hist=this.lab.slice();this.osc=[];this.gain=[];this.last=performance.now();requestAnimationFrame(t=>this.frame(t));}
  ensureAudio(){if(!audio.ctx||this.osc.length)return;for(let i=0;i<8;i++){const o=audio.ctx.createOscillator(),g=audio.ctx.createGain(),p=audio.ctx.createStereoPanner();o.type=i%3===1?'triangle':'sine';g.gain.value=0;o.connect(g);g.connect(p);p.connect(audio.master);p.pan.value=lerp(-.75,.75,i/7);o.start();this.osc.push(o);this.gain.push(g);}}
  reset(){this.adapt=this.lab.slice();this.hist=this.lab.slice();}
  tick(dt){this.lab=rgbLab(hexRgb(this.hex));const speed=lerp(1.4,.025,this.memory);for(let i=0;i<3;i++)this.adapt[i]+= (this.lab[i]-this.adapt[i])*(1-Math.exp(-dt*speed));const diff=this.lab.map((v,i)=>v-this.adapt[i]);if(this.engine==='hysteresis'){for(let i=0;i<3;i++)this.hist[i]+=diff[i]*dt*.13;for(let i=0;i<3;i++)this.hist[i]*=Math.exp(-dt*.02);}const L=this.lab[0]/100,a=this.lab[1],b=this.lab[2],C=Math.sqrt(a*a+b*b),h=Math.atan2(b,a);let state;if(this.engine==='direct')state=[L,a/128,b/128];else if(this.engine==='after')state=[(this.lab[0]-this.adapt[0])/60,diff[1]/80,diff[2]/80];else if(this.engine==='hysteresis')state=[L,this.hist[1]/50,this.hist[2]/50];else state=[L,diff[1]/90,diff[2]/90];const base=32+L*78;for(let i=0;i<8;i++){let ratio=[1,1.25,1.5,2,2.5,3.02,4.01,5.03][i];ratio*=Math.pow(2,(Math.sin(h+i*.61)*C/128)*(.08+.22*this.rough));const hz=clamp(base*ratio*(1+state[1]*.05*Math.sin(i*1.7)+state[2]*.05*Math.cos(i*.9)),18,5000);const amp=(.006+.025*this.drone)*(1/(1+i*.18))*(.3+.7*clamp(L+.2));if(this.osc[i]){this.osc[i].frequency.setTargetAtTime(hz,audio.ctx.currentTime,.08);this.gain[i].gain.setTargetAtTime(amp,audio.ctx.currentTime,.12);}}
    const rgb=hexRgb(this.hex).map(v=>Math.round(v*255));this.field.style.background=`radial-gradient(circle, rgba(${rgb.join(',')},.76), rgba(${rgb.join(',')},.09) 55%, transparent 73%)`;this.core.style.color=this.hex;this.info={L:this.lab[0],a:this.lab[1],b:this.lab[2],C,h:h*180/Math.PI,dE:Math.hypot(...diff)};}
  frame(t){const dt=Math.min(.05,(t-this.last)/1000);this.last=t;this.tick(dt);requestAnimationFrame(x=>this.frame(x));}
}

const star=new StarLab(document.querySelector('#starCanvas'));
const wheel=new WheelLab(document.querySelector('#wheelCanvas'));
const color=new ColorLab(document.querySelector('#colorField'),document.querySelector('#colorCore'));

for(const b of document.querySelectorAll('.tab'))b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view));};
const $=s=>document.querySelector(s);
$('#audioButton').onclick=async()=>{await audio.start();wheel.ensureAudio();color.ensureAudio();$('#audioButton').textContent='AUDIO ON';$('#recordButton').disabled=false;};
$('#recordButton').onclick=()=>{if(audio.recorder){audio.stopRecord();$('#recordButton').textContent='REC';}else if(audio.beginRecord())$('#recordButton').textContent='STOP';};
$('#starEngine').onchange=e=>star.engine=e.target.value;$('#starDensity').oninput=e=>{star.density=+e.target.value;star.rebuildEdges()};$('#starMotion').oninput=e=>star.motion=+e.target.value;$('#starTone').oninput=e=>star.tone=+e.target.value;$('#starFreeze').onclick=()=>{star.freeze=!star.freeze;$('#starFreeze').textContent=star.freeze?'UNFREEZE':'FREEZE'};$('#starSeed').onclick=()=>star.seed();
$('#wheelEngine').onchange=e=>wheel.engine=e.target.value;$('#wheelFriction').oninput=e=>wheel.friction=+e.target.value;$('#wheelSpread').oninput=e=>wheel.spread=+e.target.value;$('#wheelDrive').oninput=e=>wheel.drive=+e.target.value;$('#wheelImpulse').onclick=()=>{wheel.omega+=rand(-1,1)>0?rand(10,24):rand(-24,-10)};
$('#colorEngine').onchange=e=>color.engine=e.target.value;$('#colorInput').oninput=e=>color.hex=e.target.value;$('#colorMemory').oninput=e=>color.memory=+e.target.value;$('#colorDrone').oninput=e=>color.drone=+e.target.value;$('#colorRough').oninput=e=>color.rough=+e.target.value;$('#colorReset').onclick=()=>color.reset();
setInterval(()=>{$('#starInfo').textContent=`edges ${star.edges.length}\nengine ${star.engine}\nvisible nodes 12\ninternal phases 3` ;$('#wheelInfo').textContent=`angle ${mod(wheel.angle,TAU).toFixed(2)}\nvelocity ${wheel.omega.toFixed(2)} rad/s\nvirtual wheels ${wheel.teeth.length}\nteeth ${wheel.teeth.join(' ')}`;const q=color.info||{};$('#colorInfo').textContent=`L* ${(q.L||0).toFixed(1)}\na* ${(q.a||0).toFixed(1)}\nb* ${(q.b||0).toFixed(1)}\nchroma ${(q.C||0).toFixed(1)}\nhue ${(q.h||0).toFixed(1)}°\nΔE ${(q.dE||0).toFixed(1)}`;},160);
